// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			shift(4), /* find */
			nil,      /* with */
			nil,      /* id */
			nil,      /* at */
			nil,      /* author */
			nil,      /* title */
			shift(5), /* textsearch */
			nil,      /* timerange */
			nil,      /* -- */
			nil,      /* space */
			nil,      /* : */
			nil,      /* int_lit */
			nil,      /* dayMonth */
			nil,      /* number */
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			nil,          /* find */
			nil,          /* with */
			nil,          /* id */
			nil,          /* at */
			nil,          /* author */
			nil,          /* title */
			nil,          /* textsearch */
			nil,          /* timerange */
			nil,          /* -- */
			nil,          /* space */
			nil,          /* : */
			nil,          /* int_lit */
			nil,          /* dayMonth */
			nil,          /* number */
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: Start */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(2), /* $, reduce: Start */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			shift(9),  /* author */
			shift(10), /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(11), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(13), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(15), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			shift(16), /* author */
			shift(17), /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(15), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			reduce(5), /* space, reduce: AuthorKeyWord */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			reduce(7), /* space, reduce: TitleKeyWord */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			reduce(22), /* author, reduce: Space */
			reduce(22), /* title, reduce: Space */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			shift(19), /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			reduce(22), /* id, reduce: Space */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			shift(20), /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			reduce(22), /* with, reduce: Space */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			reduce(6), /* space, reduce: AuthorKeyWord */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			reduce(8), /* space, reduce: TitleKeyWord */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			shift(21), /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(15), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(13), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(13), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			shift(25), /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			shift(26), /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			shift(27), /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(13), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			shift(32), /* timerange */
			nil,       /* -- */
			shift(33), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(35), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			shift(36), /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			shift(37), /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(35), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(43), /* space */
			nil,       /* : */
			shift(45), /* int_lit */
			shift(46), /* dayMonth */
			shift(47), /* number */
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(12), /* space, reduce: TimeRangeKeyWord */
			nil,        /* : */
			reduce(12), /* int_lit, reduce: TimeRangeKeyWord */
			reduce(12), /* dayMonth, reduce: TimeRangeKeyWord */
			reduce(12), /* number, reduce: TimeRangeKeyWord */
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			reduce(22), /* timerange, reduce: Space */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			shift(48), /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			reduce(22), /* at, reduce: Space */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(10), /* $, reduce: TextSearch */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			shift(35),  /* space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(13), /* space, reduce: TimeRangeKeyWord */
			nil,        /* : */
			reduce(13), /* int_lit, reduce: TimeRangeKeyWord */
			reduce(13), /* dayMonth, reduce: TimeRangeKeyWord */
			reduce(13), /* number, reduce: TimeRangeKeyWord */
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			shift(50), /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			shift(45), /* int_lit */
			shift(46), /* dayMonth */
			shift(47), /* number */
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(11), /* space, reduce: TimeRange */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			shift(52), /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(43), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			reduce(22), /* int_lit, reduce: Space */
			reduce(22), /* dayMonth, reduce: Space */
			reduce(22), /* number, reduce: Space */
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			shift(45), /* int_lit */
			shift(46), /* dayMonth */
			shift(47), /* number */
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			reduce(19), /* int_lit, reduce: Number */
			reduce(19), /* dayMonth, reduce: Number */
			reduce(19), /* number, reduce: Number */
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			reduce(20), /* int_lit, reduce: Number */
			reduce(20), /* dayMonth, reduce: Number */
			reduce(20), /* number, reduce: Number */
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			reduce(21), /* int_lit, reduce: Number */
			reduce(21), /* dayMonth, reduce: Number */
			reduce(21), /* number, reduce: Number */
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(56), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			shift(57), /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(56), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			shift(45), /* int_lit */
			shift(46), /* dayMonth */
			shift(47), /* number */
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(43), /* space */
			nil,       /* : */
			shift(45), /* int_lit */
			shift(46), /* dayMonth */
			shift(47), /* number */
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			shift(64), /* int_lit */
			shift(65), /* dayMonth */
			shift(66), /* number */
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			shift(68), /* int_lit */
			shift(69), /* dayMonth */
			shift(70), /* number */
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			shift(32), /* timerange */
			nil,       /* -- */
			shift(33), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			reduce(22), /* timerange, reduce: Space */
			nil,        /* -- */
			reduce(22), /* space, reduce: Space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(56), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			shift(32), /* timerange */
			nil,       /* -- */
			shift(33), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			shift(68), /* int_lit */
			shift(69), /* dayMonth */
			shift(70), /* number */
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(14), /* space, reduce: DateTimeInterval */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(43), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(77), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			shift(78), /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			reduce(19), /* :, reduce: Number */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			reduce(20), /* :, reduce: Number */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			reduce(21), /* :, reduce: Number */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(16), /* space, reduce: Date */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(19), /* space, reduce: Number */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(20), /* space, reduce: Number */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(21), /* space, reduce: Number */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(4), /* $, reduce: Find */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(43), /* space */
			nil,       /* : */
			shift(45), /* int_lit */
			shift(46), /* dayMonth */
			shift(47), /* number */
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			shift(32), /* timerange */
			nil,       /* -- */
			shift(33), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(3), /* $, reduce: Find */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(17), /* space, reduce: Date */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			shift(64), /* int_lit */
			shift(65), /* dayMonth */
			shift(66), /* number */
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			reduce(15), /* --, reduce: DateTime */
			nil,        /* space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			shift(64), /* int_lit */
			shift(65), /* dayMonth */
			shift(66), /* number */
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(11), /* $, reduce: TimeRange */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			shift(84), /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(9), /* $, reduce: TextSearch */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(85), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			shift(86), /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(43), /* space */
			nil,       /* : */
			shift(45), /* int_lit */
			shift(46), /* dayMonth */
			shift(47), /* number */
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(15), /* space, reduce: DateTime */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			shift(68), /* int_lit */
			shift(69), /* dayMonth */
			shift(70), /* number */
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(14), /* $, reduce: DateTimeInterval */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(43), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			reduce(18), /* space, reduce: TimeHMS */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			nil,       /* space */
			nil,       /* : */
			shift(64), /* int_lit */
			shift(65), /* dayMonth */
			shift(66), /* number */
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* find */
			nil,       /* with */
			nil,       /* id */
			nil,       /* at */
			nil,       /* author */
			nil,       /* title */
			nil,       /* textsearch */
			nil,       /* timerange */
			nil,       /* -- */
			shift(92), /* space */
			nil,       /* : */
			nil,       /* int_lit */
			nil,       /* dayMonth */
			nil,       /* number */
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(15), /* $, reduce: DateTime */
			nil,        /* find */
			nil,        /* with */
			nil,        /* id */
			nil,        /* at */
			nil,        /* author */
			nil,        /* title */
			nil,        /* textsearch */
			nil,        /* timerange */
			nil,        /* -- */
			nil,        /* space */
			nil,        /* : */
			nil,        /* int_lit */
			nil,        /* dayMonth */
			nil,        /* number */
		},
	},
}
