
// Code generated by gocc; DO NOT EDIT.

package parser

type(
	actionTable [numStates]actionRow
	actionRow struct {
		canRecover bool
		actions [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(5),		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			shift(6),		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			accept(true),		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(1),		/* $, reduce: Start */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(2),		/* $, reduce: Start */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(3),		/* $, reduce: Start */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			shift(10),		/* author */
			shift(11),		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(12),		/* space */
			
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(14),		/* space */
			
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(16),		/* space */
			
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			shift(17),		/* author */
			shift(18),		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(16),		/* space */
			
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(8),		/* space, reduce: AuthorKeyWord */
			
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(10),		/* space, reduce: TitleKeyWord */
			
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			reduce(27),		/* author, reduce: Space */
			reduce(27),		/* title, reduce: Space */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			shift(20),		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			reduce(27),		/* id, reduce: Space */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			shift(21),		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			reduce(27),		/* with, reduce: Space */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(9),		/* space, reduce: AuthorKeyWord */
			
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(11),		/* space, reduce: TitleKeyWord */
			
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			shift(22),		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(16),		/* space */
			
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(14),		/* space */
			
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(14),		/* space */
			
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			shift(26),		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			shift(27),		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			shift(28),		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(14),		/* space */
			
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(31),		/* space */
			
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(31),		/* space */
			
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			shift(33),		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			shift(34),		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			reduce(27),		/* at, reduce: Space */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			shift(35),		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(13),		/* $, reduce: TextSearch */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(31),		/* space */
			
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(38),		/* space */
			
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(38),		/* space */
			
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			shift(40),		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			shift(44),		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(45),		/* space */
			
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			reduce(27),		/* timerange, reduce: Space */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(27),		/* space, reduce: Space */
			
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			shift(44),		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(45),		/* space */
			
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(38),		/* space */
			
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			shift(48),		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(4),		/* $, reduce: FindAuthor */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(50),		/* space */
			
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(56),		/* int_lit */
			shift(57),		/* dayMonth */
			shift(58),		/* number */
			shift(59),		/* space */
			
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			reduce(16),		/* int_lit, reduce: TimeRangeKeyWord */
			reduce(16),		/* dayMonth, reduce: TimeRangeKeyWord */
			reduce(16),		/* number, reduce: TimeRangeKeyWord */
			reduce(16),		/* space, reduce: TimeRangeKeyWord */
			
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			reduce(27),		/* timerange, reduce: Space */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(6),		/* $, reduce: FindTitle */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(50),		/* space */
			
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			shift(44),		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(45),		/* space */
			
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			reduce(17),		/* int_lit, reduce: TimeRangeKeyWord */
			reduce(17),		/* dayMonth, reduce: TimeRangeKeyWord */
			reduce(17),		/* number, reduce: TimeRangeKeyWord */
			reduce(17),		/* space, reduce: TimeRangeKeyWord */
			
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(5),		/* $, reduce: FindAuthor */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(27),		/* $, reduce: Space */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(56),		/* int_lit */
			shift(57),		/* dayMonth */
			shift(58),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(14),		/* $, reduce: TimeRange */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(65),		/* space */
			
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			shift(66),		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(59),		/* space */
			
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(56),		/* int_lit */
			shift(57),		/* dayMonth */
			shift(58),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			reduce(24),		/* int_lit, reduce: Number */
			reduce(24),		/* dayMonth, reduce: Number */
			reduce(24),		/* number, reduce: Number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			reduce(25),		/* int_lit, reduce: Number */
			reduce(25),		/* dayMonth, reduce: Number */
			reduce(25),		/* number, reduce: Number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			reduce(26),		/* int_lit, reduce: Number */
			reduce(26),		/* dayMonth, reduce: Number */
			reduce(26),		/* number, reduce: Number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			reduce(27),		/* int_lit, reduce: Space */
			reduce(27),		/* dayMonth, reduce: Space */
			reduce(27),		/* number, reduce: Space */
			nil,		/* space */
			
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(7),		/* $, reduce: FindTitle */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(12),		/* $, reduce: TextSearch */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(56),		/* int_lit */
			shift(57),		/* dayMonth */
			shift(58),		/* number */
			shift(59),		/* space */
			
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(56),		/* int_lit */
			shift(57),		/* dayMonth */
			shift(58),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: TimeRange */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(15),		/* space, reduce: TimeRange */
			
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(27),		/* $, reduce: Space */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(27),		/* space, reduce: Space */
			
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(56),		/* int_lit */
			shift(57),		/* dayMonth */
			shift(58),		/* number */
			shift(59),		/* space */
			
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(75),		/* int_lit */
			shift(76),		/* dayMonth */
			shift(77),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(79),		/* int_lit */
			shift(80),		/* dayMonth */
			shift(81),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(14),		/* $, reduce: TimeRange */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(50),		/* space */
			
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(79),		/* int_lit */
			shift(80),		/* dayMonth */
			shift(81),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: DateTimeInterval */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(18),		/* space, reduce: DateTimeInterval */
			
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(59),		/* space */
			
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			reduce(19),		/* --, reduce: DateTime */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(86),		/* space */
			
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			shift(87),		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			reduce(24),		/* :, reduce: Number */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			reduce(25),		/* :, reduce: Number */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			reduce(26),		/* :, reduce: Number */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(21),		/* space, reduce: Date */
			
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(24),		/* space, reduce: Number */
			
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(25),		/* space, reduce: Number */
			
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(26),		/* space, reduce: Number */
			
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: TimeRange */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(22),		/* space, reduce: Date */
			
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(75),		/* int_lit */
			shift(76),		/* dayMonth */
			shift(77),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			reduce(20),		/* --, reduce: DateTime */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			reduce(27),		/* --, reduce: Space */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(75),		/* int_lit */
			shift(76),		/* dayMonth */
			shift(77),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: DateTime */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			shift(65),		/* space */
			
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			shift(92),		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			shift(93),		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: DateTime */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(20),		/* space, reduce: DateTime */
			
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(75),		/* int_lit */
			shift(76),		/* dayMonth */
			shift(77),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(96),		/* int_lit */
			shift(97),		/* dayMonth */
			shift(98),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			shift(99),		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			reduce(23),		/* --, reduce: TimeHMS */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(23),		/* space, reduce: TimeHMS */
			
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			reduce(24),		/* --, reduce: Number */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(24),		/* space, reduce: Number */
			
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			reduce(25),		/* --, reduce: Number */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(25),		/* space, reduce: Number */
			
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			reduce(26),		/* --, reduce: Number */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(26),		/* space, reduce: Number */
			
		},
	},
	actionRow{ // S99
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			shift(101),		/* int_lit */
			shift(102),		/* dayMonth */
			shift(103),		/* number */
			nil,		/* space */
			
		},
	},
	actionRow{ // S100
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(23),		/* $, reduce: TimeHMS */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(23),		/* space, reduce: TimeHMS */
			
		},
	},
	actionRow{ // S101
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(24),		/* $, reduce: Number */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(24),		/* space, reduce: Number */
			
		},
	},
	actionRow{ // S102
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Number */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(25),		/* space, reduce: Number */
			
		},
	},
	actionRow{ // S103
		canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(26),		/* $, reduce: Number */
			nil,		/* find */
			nil,		/* with */
			nil,		/* id */
			nil,		/* at */
			nil,		/* author */
			nil,		/* title */
			nil,		/* textsearch */
			nil,		/* timerange */
			nil,		/* -- */
			nil,		/* : */
			nil,		/* int_lit */
			nil,		/* dayMonth */
			nil,		/* number */
			reduce(26),		/* space, reduce: Number */
			
		},
	},
	
}

