
// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 15
type(
	gotoTable [numStates]gotoRow
	gotoRow	[numNTSymbols] int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1, // Start
		2, // FindAuthor
		3, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		4, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		7, // AuthorKeyWord
		9, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		8, // Space
		
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		13, // Space
		
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		15, // Space
		
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		19, // Space
		
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		23, // Space
		
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		24, // Space
		
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		25, // Space
		
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		29, // Space
		
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		30, // Space
		
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		32, // Space
		
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S31
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		36, // Space
		
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		37, // Space
		
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		39, // Space
		
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		42, // TimeRange
		43, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		41, // Space
		
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		46, // TimeRange
		43, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		41, // Space
		
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		47, // Space
		
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		49, // Space
		
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		52, // DateTimeInterval
		53, // DateTime
		54, // Date
		-1, // TimeHMS
		55, // Number
		51, // Space
		
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		60, // Space
		
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		61, // TimeRange
		62, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		41, // Space
		
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S49
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S50
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		63, // Number
		-1, // Space
		
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		64, // Space
		
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		67, // Space
		
	},
	gotoRow{ // S55
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		68, // Number
		-1, // Space
		
	},
	gotoRow{ // S56
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S57
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S58
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S59
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S60
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S61
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S62
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		69, // DateTimeInterval
		53, // DateTime
		54, // Date
		-1, // TimeHMS
		55, // Number
		51, // Space
		
	},
	gotoRow{ // S63
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		70, // Number
		-1, // Space
		
	},
	gotoRow{ // S64
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S65
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S66
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		71, // DateTime
		72, // Date
		-1, // TimeHMS
		55, // Number
		51, // Space
		
	},
	gotoRow{ // S67
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		73, // TimeHMS
		74, // Number
		-1, // Space
		
	},
	gotoRow{ // S68
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		78, // Number
		-1, // Space
		
	},
	gotoRow{ // S69
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		82, // Space
		
	},
	gotoRow{ // S70
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		83, // Number
		-1, // Space
		
	},
	gotoRow{ // S71
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S72
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		84, // Space
		
	},
	gotoRow{ // S73
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		85, // Space
		
	},
	gotoRow{ // S74
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S75
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S76
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S77
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S78
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S79
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S80
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S81
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S82
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S83
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S84
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		88, // TimeHMS
		89, // Number
		-1, // Space
		
	},
	gotoRow{ // S85
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S86
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S87
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		90, // Number
		-1, // Space
		
	},
	gotoRow{ // S88
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		91, // Space
		
	},
	gotoRow{ // S89
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S90
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S91
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S92
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		94, // Number
		-1, // Space
		
	},
	gotoRow{ // S93
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		95, // Number
		-1, // Space
		
	},
	gotoRow{ // S94
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S95
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S96
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S97
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S98
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S99
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		100, // Number
		-1, // Space
		
	},
	gotoRow{ // S100
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S101
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S102
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	gotoRow{ // S103
		-1, // S'
		-1, // Start
		-1, // FindAuthor
		-1, // FindTitle
		-1, // AuthorKeyWord
		-1, // TitleKeyWord
		-1, // TextSearch
		-1, // TimeRange
		-1, // TimeRangeKeyWord
		-1, // DateTimeInterval
		-1, // DateTime
		-1, // Date
		-1, // TimeHMS
		-1, // Number
		-1, // Space
		
	},
	
}
